name: Development Branch Build & Test

on:
  push:
    branches:
      - develop   
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108 
        
    - name: Checkout /develop/
      run:  |
        git checkout develop 
        
    - name: Build with dotnet
      run: dotnet build --configuration Release KinoImip/KinoImipCore/KinoImipCore.csproj

    - name: Run unit tests
      run: dotnet test KinoImip/KinoImipTests/KinoImipTests.csproj
